---
title: "build_runs function putting the pieces together"
output: html_document
date: "2023-04-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("/capstone/firefutures/data_cleaning/packages.R")
source("/capstone/firefutures/data_cleaning/cal_adapt_4models_allscenarios.R")
```

1. find df (WORKING) 
This is the first step in the process of building a run where we get our starting dataframe
```{r}
# Define function to extract data from a particular GCM and RCP scenario for a specific sample cell
find_df <- function(rcp, gcm, sample_cell) {
  
  # Define the valid GCM options
  valid_gcms <- c("MIROC5", "HadGEM2ES", "CanESM2", "CNRM_CM5")
  
  # Check if input gcm is valid. If not, return an error message.
  if (!gcm %in% valid_gcms) {
    stop("Invalid value for gcm. Allowed options are: ", paste(valid_gcms, collapse = ", "))
  }
  
  # Ensure that input rcp is numeric
  rcp <- as.numeric(rcp)
  
  # Check if input rcp is valid (either 45 or 85). If not, return an error message.
  if (!rcp %in% c(45, 85)) {
    stop("Invalid value for rcp. Only 45 or 85 are allowed.")
  }
  
  # Construct the name of the data frame to extract, based on the input GCM and RCP values
  df_name <- paste(gcm, paste0("rcp", rcp), sep = "_")
  
  # Extract the data frame from the global environment, using the constructed name
  df <- get(df_name, envir = globalenv())
  
  # Get the names of the columns in the data frame that correspond to the specified sample cell
  var_names <- grep(paste0("_", sample_cell, "$"), names(df), value = TRUE)
  
  # Select the time column and the columns corresponding to the specified sample cell,
  # and rename the columns to remove the sample cell suffix
  combined_df <- select(df, time, one_of(var_names)) %>%
    rename_all( ~ gsub(paste0("_", sample_cell, "$"), "", .))
  
  # Return the resulting data frame
  return(combined_df)
}

# Example usage of the function
df_example <- find_df(45, "MIROC5", 2)
```

2. filter to correct dates (WORKING)
```{r}
sample_window <- function(start_date, sample_window, df) {
  start_date <- as.Date(start_date, format = "%m/%d/%Y") # Convert start_date to date format
  
  start <- (start_date - years(sample_window)) # Calculate the first year in the sampling window
  end <- (start_date + years(sample_window)) # Calculate the last year in the sampling window
  
  # Check if sample_window argument is not NULL
  if (!is.null(sample_window)) {
    # Filter the data frame based on the start and end dates
    df <- df %>% filter(time >= start & time <= end)
  } else {
    df <- df
    # If sample_window is NULL, issue a warning and return the entire data frame
    warning("sample_window argument is NULL. Specify sampling window, or else we'll pull from 1950-2100.")
  }
}

sample_window_example <- sample_window('04/07/2023', 10, df_example)
```

3. create climate variable table (USING FOR PRACTICE BELOW)
```{r}
climate_vars <-
  data.frame(
    variable = c('wind', 'precip', 'max_temp'),
    lower = c(.1, .1, .50),
    upper = c(.90, .90, .90)
  )
```

4. filter one year on climate table (WORKING)
```{r}
filter_df <- function(df, climate_table) {
  df <- df %>% group_by(year = lubridate::year(time)) %>% summarise(wind = mean(wind),
                                                                    max_temp = mean(max_temp),
                                                                    min_temp = mean(min_temp),
                                                                    precip = sum(precip),
                                                                    min_humidity = mean(min_humidity),
                                                                    max_humidity = mean(max_humidity))
   
 for (j in 1:nrow(climate_table)) {
    climate_var <- climate_table[j, "variable"]
    lower <- climate_table[j, "lower"] 
    upper <- climate_table[j, "upper"]

    lower_perc <- quantile(df[[climate_var]], lower, na.rm = TRUE)

    upper_perc <- quantile(df[[climate_var]], upper, na.rm = TRUE)

    df <- df %>% filter(!is.na(!!sym(climate_var)), !!sym(climate_var) >= lower_perc, !!sym(climate_var) <= upper_perc)
 }
return(df$year)
}

test <- filter_df(sample_window_example, climate_vars)
```

```{r}
#creating a list for practice below
climate_vars_list <- list(
  data.frame(
    variable = c('wind', 'precip', 'max_temp'),
    lower = c(.1, .1, .1),
    upper = c(.99, .99, .99)
  ),
  data.frame(
    variable = c('min_temp'),
    lower = c(.55),
    upper = c(.85)
  ),
  data.frame(
    variable = c('wind', 'precip', 'max_temp'),
    lower = c(.2, .2, .6),
    upper = c(.80, .80, .80)
  ),
  data.frame(
    variable = c('wind', 'precip', 'max_temp'),
    lower = c(.25, .25, .65),
    upper = c(.75, .75, .75)
  ),
  data.frame(
    variable = c('wind'),
    lower = (.1),
    upper = (.9)
  )
)
```

5. Putting it all together for year
```{r}
filter_year <- function(rcp,
                        gcm,
                        sample_cell,
                        run_type,
                        start_date,
                        duration,
                        climate_table,
                        sample_window) {
  our_gcm <- find_df(rcp, gcm, sample_cell)
  
  df_list <- list()
  
  for (i in 1:length(climate_vars_list)) {
    start_date <- as.Date(start_date, format = "%m/%d/%Y")
    
    df <- sample_window(start_date, duration, our_gcm)
    
    # Call filter_df at index i of the climate variables list
    years <- filter_df(df, climate_table[[i]])
    
    # Appends the output to the df_list
    df_list[[i]] <- years
    print(df_list)
    start_date <- start_date + years(1) # Add one year to start_date
  }
  
#Returns the list of filtered years for each data frame that can be put into the stitches function
  return(df_list)
}
#Example for creating a list for the desired years and gcm
run_samples <-
  filter_year(
    rcp = 45,
    gcm = "MIROC5",
    sample_cell = 2,
    start_date = '04/07/2023',
    sample_window = 10,
    duration = 10,
    climate_table = climate_vars_list
  )
```

```{r}
# season_def <- list(wet_season = c(11, 12, 1, 2, 3, 4), dry_season = c(11, 12, 1, 2, 3, 4))
# 
# # 
# # add_season <- function(data, season, months ) {
# #   
# # data <- data %>% mutate(season = ifelse(lubridate::month(time) %in%  c(11, 12, 1, 2, 3, 4), "wet", "dry"))
# # }
# 
# add_season <- function(data, season_def) {
#   
#   data <- data %>% mutate(season = ifelse(lubridate::month(time) %in%  c(11, 12, 1, 2, 3, 4), "wet", "dry")))
#   
#   return(data)
# }
# 
# season <- add_season(sample_window_example, season_def)
```

```{r}
filter_season <- function(rcp,
                        gcm,
                        sample_cell,
                        run_type,
                        start_date,
                        duration,
                        climate_table,
                        sample_window) {
  our_gcm <- find_df(rcp, gcm, sample_cell)
  our_gcm <- add_season(our_gcm)
  print(our_gcm)
  
  df_list <- list()
  
  for (i in 1:length(climate_vars_list)) {
  start_date <- as.Date(start_date, format = "%m/%d/%Y")
  
  df <- sample_window(start_date, duration, our_gcm)mir
  }
}

test <- filter_season(rcp = 45, gcm = "MIROC5", sample_cell = 2)
```

